"""intial commit

Revision ID: 85382ac6354d
Revises: 
Create Date: 2026-03-18 17:20:09.380906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85382ac6354d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('node_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('property_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('location_type_business', sa.String(length=100), nullable=False),
    sa.Column('city_division_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_table('sublocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sublocations_id'), 'sublocations', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('project_grade', sa.String(length=100), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sublocation_id', sa.Integer(), nullable=True),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('google_map_url', sa.String(length=500), nullable=True),
    sa.Column('address_line1', sa.String(length=100), nullable=False),
    sa.Column('address_line2', sa.String(length=100), nullable=True),
    sa.Column('total_property_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_property_area_unit', sa.String(length=20), nullable=True),
    sa.Column('property_sanction_type', sa.String(length=100), nullable=True),
    sa.Column('tenant_profile', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.ForeignKeyConstraint(['sublocation_id'], ['sublocations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_property_city_location', 'properties', ['city_id', 'location_id'], unique=False)
    op.create_index('idx_property_type_city', 'properties', ['property_type_id', 'city_id'], unique=False)
    op.create_index(op.f('ix_properties_city_id'), 'properties', ['city_id'], unique=False)
    op.create_index(op.f('ix_properties_location_id'), 'properties', ['location_id'], unique=False)
    op.create_index(op.f('ix_properties_property_type_id'), 'properties', ['property_type_id'], unique=False)
    op.create_index(op.f('ix_properties_sublocation_id'), 'properties', ['sublocation_id'], unique=False)
    op.create_table('property_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('node_type_id', sa.Integer(), nullable=False),
    sa.Column('parent_node_id', sa.UUID(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_type_id'], ['node_types.id'], ),
    sa.ForeignKeyConstraint(['parent_node_id'], ['property_nodes.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_ordering', 'property_nodes', ['parent_node_id', 'sequence_order'], unique=False)
    op.create_index('idx_property_node_hierarchy', 'property_nodes', ['property_id', 'parent_node_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_property_nodes_node_type_id'), 'property_nodes', ['node_type_id'], unique=False)
    op.create_index(op.f('ix_property_nodes_parent_node_id'), 'property_nodes', ['parent_node_id'], unique=False)
    op.create_index(op.f('ix_property_nodes_property_id'), 'property_nodes', ['property_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('building_name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=100), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('total_area_unit', sa.String(length=20), nullable=False),
    sa.Column('power_backup', sa.Boolean(), nullable=False),
    sa.Column('green_rating', sa.String(length=100), nullable=False),
    sa.Column('parking_ratio', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('floor_name', sa.String(length=100), nullable=False),
    sa.Column('floor_area', sa.Float(), nullable=False),
    sa.Column('floor_area_unit', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_table('industrial_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('industrial_name', sa.String(length=100), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('total_area_unit', sa.String(length=20), nullable=False),
    sa.Column('ceiling_height', sa.Float(), nullable=True),
    sa.Column('dock_doors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index(op.f('ix_industrial_details_id'), 'industrial_details', ['id'], unique=False)
    op.create_table('land_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('land_name', sa.String(length=100), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('total_area_unit', sa.String(length=20), nullable=False),
    sa.Column('zoning_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index(op.f('ix_land_details_id'), 'land_details', ['id'], unique=False)
    op.create_table('logistics_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('logistics_name', sa.String(length=100), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('total_area_unit', sa.String(length=20), nullable=False),
    sa.Column('truck_bays', sa.Integer(), nullable=True),
    sa.Column('loading_docks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index(op.f('ix_logistics_details_id'), 'logistics_details', ['id'], unique=False)
    op.create_table('retail_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('retail_unit_name', sa.String(length=100), nullable=False),
    sa.Column('unit_area', sa.Float(), nullable=False),
    sa.Column('unit_area_unit', sa.String(length=20), nullable=False),
    sa.Column('frontage', sa.Float(), nullable=True),
    sa.Column('rental', sa.Float(), nullable=True),
    sa.Column('rental_unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id')
    )
    op.create_index(op.f('ix_retail_units_id'), 'retail_units', ['id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('unit_name', sa.String(length=100), nullable=False),
    sa.Column('unit_area', sa.Float(), nullable=False),
    sa.Column('unit_area_unit', sa.String(length=10), nullable=False),
    sa.Column('chargeable_area', sa.Float(), nullable=False),
    sa.Column('chargeable_area_unit', sa.String(length=10), nullable=False),
    sa.Column('carpet_area', sa.Float(), nullable=False),
    sa.Column('carpet_area_unit', sa.String(length=30), nullable=False),
    sa.Column('rental', sa.Float(), nullable=False),
    sa.Column('rental_unit', sa.String(length=30), nullable=False),
    sa.Column('notice_period', sa.Integer(), nullable=False),
    sa.Column('notice_period_unit', sa.String(length=30), nullable=False),
    sa.Column('cam_charges', sa.Float(), nullable=False),
    sa.Column('cam_charges_unit', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_table('wings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('wing_name', sa.String(length=100), nullable=False),
    sa.Column('independent_entrance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['property_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wings_id'), 'wings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wings_id'), table_name='wings')
    op.drop_table('wings')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_retail_units_id'), table_name='retail_units')
    op.drop_table('retail_units')
    op.drop_index(op.f('ix_logistics_details_id'), table_name='logistics_details')
    op.drop_table('logistics_details')
    op.drop_index(op.f('ix_land_details_id'), table_name='land_details')
    op.drop_table('land_details')
    op.drop_index(op.f('ix_industrial_details_id'), table_name='industrial_details')
    op.drop_table('industrial_details')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_property_nodes_property_id'), table_name='property_nodes')
    op.drop_index(op.f('ix_property_nodes_parent_node_id'), table_name='property_nodes')
    op.drop_index(op.f('ix_property_nodes_node_type_id'), table_name='property_nodes')
    op.drop_index('idx_property_node_hierarchy', table_name='property_nodes')
    op.drop_index('idx_node_ordering', table_name='property_nodes')
    op.drop_table('property_nodes')
    op.drop_index(op.f('ix_properties_sublocation_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_location_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city_id'), table_name='properties')
    op.drop_index('idx_property_type_city', table_name='properties')
    op.drop_index('idx_property_city_location', table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_sublocations_id'), table_name='sublocations')
    op.drop_table('sublocations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('property_types')
    op.drop_table('node_types')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
