"""fix sublocation unique constraint

Revision ID: be2c68441615
Revises: f6633a102c53
Create Date: 2026-04-02 10:52:36.317352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2c68441615'
down_revision: Union[str, Sequence[str], None] = 'f6633a102c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sublocations_name_key'), 'sublocations', type_='unique')
    op.create_unique_constraint('uq_sublocation_name_location', 'sublocations', ['name', 'location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sublocation_name_location', 'sublocations', type_='unique')
    op.create_unique_constraint(op.f('sublocations_name_key'), 'sublocations', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
