from sqlalchemy.orm import Session
from app.models.properties import Location


def seed_locations(db: Session):
    locations = [
        # ── Pune ─────────────────────────────────────────────────────────────
        {"id": 1,   "name": "Hinjewadi",     "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Peripheral"},
        {"id": 2,   "name": "Wakad",         "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 3,   "name": "Bavdhan",       "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Peripheral"},
        {"id": 4,   "name": "Chinchwad",     "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Peripheral"},
        {"id": 5,   "name": "Balewadi",      "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 6,   "name": "Pashan",        "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 7,   "name": "Baner",         "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 8,   "name": "Kothrud",       "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 9,   "name": "Pimpri",        "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Peripheral"},
        {"id": 10,  "name": "Aundh",         "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 11,  "name": "Erandwane",     "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 12,  "name": "Khadki",        "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 13,  "name": "Shivaji Nagar", "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 14,  "name": "Peth Area",     "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 15,  "name": "Bund Garden",   "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 16,  "name": "Yerawada",      "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 17,  "name": "Koregaon Park", "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 18,  "name": "Kalyani Nagar", "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 19,  "name": "Viman Nagar",   "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 20,  "name": "Wanowrie",      "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 21,  "name": "Kharadi",       "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 22,  "name": "Hadapsar",      "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 23,  "name": "Wagholi",       "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 24,  "name": "Swargate",      "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        {"id": 25,  "name": "Kondhwa",       "city_id": 1, "city_division_name": "West Pune", "location_type_business": "Secondary"},
        # ── Mumbai ───────────────────────────────────────────────────────────
        {"id": 26,  "name": "Andheri East",  "city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Commercial"},
        {"id": 27,  "name": "Andheri West",  "city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Commercial"},
        {"id": 28,  "name": "Bandra West",   "city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Premium"},
        {"id": 29,  "name": "Borivali East", "city_id": 2, "city_division_name": "Northern Suburbs",  "location_type_business": "Residential"},
        {"id": 30,  "name": "Borivali West", "city_id": 2, "city_division_name": "Northern Suburbs",  "location_type_business": "Residential"},
        {"id": 31,  "name": "Dadar",         "city_id": 2, "city_division_name": "Central Mumbai",   "location_type_business": "Commercial"},
        {"id": 32,  "name": "Goregaon East", "city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Residential"},
        {"id": 33,  "name": "Goregaon West", "city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Residential"},
        {"id": 34,  "name": "Juhu",          "city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Premium"},
        {"id": 35,  "name": "Kandivali East","city_id": 2, "city_division_name": "Northern Suburbs",  "location_type_business": "Residential"},
        {"id": 36,  "name": "Kandivali West","city_id": 2, "city_division_name": "Northern Suburbs",  "location_type_business": "Residential"},
        {"id": 37,  "name": "Lower Parel",   "city_id": 2, "city_division_name": "Central Mumbai",   "location_type_business": "Commercial"},
        {"id": 38,  "name": "Malad East",    "city_id": 2, "city_division_name": "Northern Suburbs",  "location_type_business": "Residential"},
        {"id": 39,  "name": "Malad West",    "city_id": 2, "city_division_name": "Northern Suburbs",  "location_type_business": "Residential"},
        {"id": 40,  "name": "Marine Lines",  "city_id": 2, "city_division_name": "South Mumbai",     "location_type_business": "Premium"},
        {"id": 41,  "name": "Navi Mumbai",   "city_id": 2, "city_division_name": "Harbour Region",   "location_type_business": "Peripheral"},
        {"id": 42,  "name": "Powai",         "city_id": 2, "city_division_name": "Eastern Suburbs",  "location_type_business": "Commercial"},
        {"id": 43,  "name": "Santacruz East","city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Residential"},
        {"id": 44,  "name": "Santacruz West","city_id": 2, "city_division_name": "Western Suburbs",  "location_type_business": "Residential"},
        {"id": 45,  "name": "Thane",         "city_id": 2, "city_division_name": "Thane District",   "location_type_business": "Peripheral"},
        {"id": 46,  "name": "Vashi",         "city_id": 2, "city_division_name": "Harbour Region",   "location_type_business": "Commercial"},
        {"id": 47,  "name": "Worli",         "city_id": 2, "city_division_name": "South Mumbai",     "location_type_business": "Premium"},
        # ── Nagpur ───────────────────────────────────────────────────────────
        {"id": 48,  "name": "Besa",              "city_id": 3, "city_division_name": "West Nagpur",    "location_type_business": "Residential"},
        {"id": 49,  "name": "Civil Lines",       "city_id": 3, "city_division_name": "Central Nagpur", "location_type_business": "Commercial"},
        {"id": 50,  "name": "Dharampeth",        "city_id": 3, "city_division_name": "Central Nagpur", "location_type_business": "Commercial"},
        {"id": 51,  "name": "Hingna",            "city_id": 3, "city_division_name": "West Nagpur",    "location_type_business": "Peripheral"},
        {"id": 52,  "name": "Jaripatka",         "city_id": 3, "city_division_name": "North Nagpur",   "location_type_business": "Residential"},
        {"id": 53,  "name": "Kalamna",           "city_id": 3, "city_division_name": "North Nagpur",   "location_type_business": "Industrial"},
        {"id": 54,  "name": "Koradi",            "city_id": 3, "city_division_name": "North Nagpur",   "location_type_business": "Peripheral"},
        {"id": 55,  "name": "Manewada",          "city_id": 3, "city_division_name": "East Nagpur",    "location_type_business": "Residential"},
        {"id": 56,  "name": "Mankapur",          "city_id": 3, "city_division_name": "East Nagpur",    "location_type_business": "Residential"},
        {"id": 57,  "name": "Nandanvan",         "city_id": 3, "city_division_name": "South Nagpur",   "location_type_business": "Residential"},
        {"id": 58,  "name": "Pardi",             "city_id": 3, "city_division_name": "South Nagpur",   "location_type_business": "Industrial"},
        {"id": 59,  "name": "Ramdaspeth",        "city_id": 3, "city_division_name": "Central Nagpur", "location_type_business": "Premium"},
        {"id": 60,  "name": "Sakkardara",        "city_id": 3, "city_division_name": "South Nagpur",   "location_type_business": "Residential"},
        {"id": 61,  "name": "Sitabuldi",         "city_id": 3, "city_division_name": "Central Nagpur", "location_type_business": "Commercial"},
        {"id": 62,  "name": "Sonegaon",          "city_id": 3, "city_division_name": "South Nagpur",   "location_type_business": "Residential"},
        {"id": 63,  "name": "Trimurti Nagar",    "city_id": 3, "city_division_name": "West Nagpur",    "location_type_business": "Residential"},
        {"id": 64,  "name": "Wardha Road",       "city_id": 3, "city_division_name": "East Nagpur",    "location_type_business": "Commercial"},
        {"id": 65,  "name": "Yashodhara Nagar",  "city_id": 3, "city_division_name": "West Nagpur",    "location_type_business": "Residential"},
        # ── Bangalore ────────────────────────────────────────────────────────
        {"id": 66,  "name": "Bellandur",         "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Commercial"},
        {"id": 67,  "name": "Bommanahalli",      "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Commercial"},
        {"id": 68,  "name": "BTM Layout",        "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Commercial"},
        {"id": 69,  "name": "Electronic City",   "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Commercial"},
        {"id": 70,  "name": "Hebbal",            "city_id": 4, "city_division_name": "North Bangalore",   "location_type_business": "Residential"},
        {"id": 71,  "name": "Hennur",            "city_id": 4, "city_division_name": "North Bangalore",   "location_type_business": "Residential"},
        {"id": 72,  "name": "HSR Layout",        "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Commercial"},
        {"id": 73,  "name": "Indiranagar",       "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Premium"},
        {"id": 74,  "name": "Jayanagar",         "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Commercial"},
        {"id": 75,  "name": "JP Nagar",          "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Residential"},
        {"id": 76,  "name": "Kalyan Nagar",      "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Residential"},
        {"id": 77,  "name": "Koramangala",       "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Premium"},
        {"id": 78,  "name": "Mahadevapura",      "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Industrial"},
        {"id": 79,  "name": "Malleshwaram",      "city_id": 4, "city_division_name": "West Bangalore",    "location_type_business": "Commercial"},
        {"id": 80,  "name": "Marathahalli",      "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Commercial"},
        {"id": 81,  "name": "Nagarbhavi",        "city_id": 4, "city_division_name": "West Bangalore",    "location_type_business": "Residential"},
        {"id": 82,  "name": "Old Airport Road",  "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Commercial"},
        {"id": 83,  "name": "Rajajinagar",       "city_id": 4, "city_division_name": "West Bangalore",    "location_type_business": "Commercial"},
        {"id": 84,  "name": "Ramamurthy Nagar",  "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Residential"},
        {"id": 85,  "name": "Sahakar Nagar",     "city_id": 4, "city_division_name": "North Bangalore",   "location_type_business": "Residential"},
        {"id": 86,  "name": "Sarjapur Road",     "city_id": 4, "city_division_name": "South Bangalore",   "location_type_business": "Commercial"},
        {"id": 87,  "name": "Thanisandra",       "city_id": 4, "city_division_name": "North Bangalore",   "location_type_business": "Residential"},
        {"id": 88,  "name": "Ulsoor",            "city_id": 4, "city_division_name": "Central Bangalore",  "location_type_business": "Premium"},
        {"id": 89,  "name": "Whitefield",        "city_id": 4, "city_division_name": "East Bangalore",    "location_type_business": "Commercial"},
        {"id": 90,  "name": "Yelahanka",         "city_id": 4, "city_division_name": "North Bangalore",   "location_type_business": "Peripheral"},
        # ── Hyderabad ─────────────────────────────────────────────────────────
        {"id": 91,  "name": "Ameerpet",          "city_id": 5, "city_division_name": "Central Hyderabad", "location_type_business": "Commercial"},
        {"id": 92,  "name": "Banjara Hills",     "city_id": 5, "city_division_name": "Central Hyderabad", "location_type_business": "Premium"},
        {"id": 93,  "name": "Begumpet",          "city_id": 5, "city_division_name": "Central Hyderabad", "location_type_business": "Commercial"},
        {"id": 94,  "name": "Boduppal",          "city_id": 5, "city_division_name": "East Hyderabad",    "location_type_business": "Residential"},
        {"id": 95,  "name": "Dilsukhnagar",      "city_id": 5, "city_division_name": "South Hyderabad",   "location_type_business": "Commercial"},
        {"id": 96,  "name": "Gachibowli",        "city_id": 5, "city_division_name": "West Hyderabad",    "location_type_business": "Commercial"},
        {"id": 97,  "name": "Hitech City",       "city_id": 5, "city_division_name": "West Hyderabad",    "location_type_business": "Commercial"},
        {"id": 98,  "name": "Jubilee Hills",     "city_id": 5, "city_division_name": "West Hyderabad",    "location_type_business": "Premium"},
        {"id": 99,  "name": "Kachiguda",         "city_id": 5, "city_division_name": "Central Hyderabad", "location_type_business": "Commercial"},
        {"id": 100, "name": "Kompally",          "city_id": 5, "city_division_name": "North Hyderabad",   "location_type_business": "Residential"},
        {"id": 101, "name": "Kondapur",          "city_id": 5, "city_division_name": "West Hyderabad",    "location_type_business": "Commercial"},
        {"id": 102, "name": "Kukatpally",        "city_id": 5, "city_division_name": "North Hyderabad",   "location_type_business": "Residential"},
        {"id": 103, "name": "Madhapur",          "city_id": 5, "city_division_name": "West Hyderabad",    "location_type_business": "Commercial"},
        {"id": 104, "name": "Manikonda",         "city_id": 5, "city_division_name": "West Hyderabad",    "location_type_business": "Residential"},
        {"id": 105, "name": "Mehdipatnam",       "city_id": 5, "city_division_name": "South Hyderabad",   "location_type_business": "Commercial"},
        {"id": 106, "name": "Miyapur",           "city_id": 5, "city_division_name": "North Hyderabad",   "location_type_business": "Residential"},
        {"id": 107, "name": "Nallagandla",       "city_id": 5, "city_division_name": "West Hyderabad",    "location_type_business": "Peripheral"},
        {"id": 108, "name": "Secunderabad",      "city_id": 5, "city_division_name": "North Hyderabad",   "location_type_business": "Commercial"},
        {"id": 109, "name": "Shamshabad",        "city_id": 5, "city_division_name": "South Hyderabad",   "location_type_business": "Peripheral"},
        {"id": 110, "name": "Uppal",             "city_id": 5, "city_division_name": "East Hyderabad",    "location_type_business": "Residential"},
        {"id": 111, "name": "Vanastalipuram",    "city_id": 5, "city_division_name": "East Hyderabad",    "location_type_business": "Residential"},
        {"id": 112, "name": "Yapral",            "city_id": 5, "city_division_name": "North Hyderabad",   "location_type_business": "Residential"},
        {"id": 113, "name": "Zoo Park",          "city_id": 5, "city_division_name": "South Hyderabad",   "location_type_business": "Residential"},
        # ── Chennai ───────────────────────────────────────────────────────────
        {"id": 114, "name": "Adyar",             "city_id": 6, "city_division_name": "South Chennai",   "location_type_business": "Premium"},
        {"id": 115, "name": "Ambattur",          "city_id": 6, "city_division_name": "West Chennai",    "location_type_business": "Industrial"},
        {"id": 116, "name": "Anna Nagar",        "city_id": 6, "city_division_name": "Central Chennai", "location_type_business": "Commercial"},
        {"id": 117, "name": "Besant Nagar",      "city_id": 6, "city_division_name": "South Chennai",   "location_type_business": "Premium"},
        {"id": 118, "name": "Chromepet",         "city_id": 6, "city_division_name": "South Chennai",   "location_type_business": "Residential"},
        {"id": 119, "name": "Egmore",            "city_id": 6, "city_division_name": "Central Chennai", "location_type_business": "Commercial"},
        {"id": 120, "name": "Guindy",            "city_id": 6, "city_division_name": "South Chennai",   "location_type_business": "Commercial"},
        {"id": 121, "name": "Kilpauk",           "city_id": 6, "city_division_name": "Central Chennai", "location_type_business": "Residential"},
        {"id": 122, "name": "KK Nagar",          "city_id": 6, "city_division_name": "West Chennai",    "location_type_business": "Residential"},
        {"id": 123, "name": "Mogappair",         "city_id": 6, "city_division_name": "West Chennai",    "location_type_business": "Residential"},
        {"id": 124, "name": "Mylapore",          "city_id": 6, "city_division_name": "Central Chennai", "location_type_business": "Premium"},
        {"id": 125, "name": "Nungambakkam",      "city_id": 6, "city_division_name": "Central Chennai", "location_type_business": "Commercial"},
        {"id": 126, "name": "OMR",               "city_id": 6, "city_division_name": "South Chennai",   "location_type_business": "Commercial"},
        {"id": 127, "name": "Perambur",          "city_id": 6, "city_division_name": "North Chennai",   "location_type_business": "Industrial"},
        {"id": 128, "name": "Porur",             "city_id": 6, "city_division_name": "West Chennai",    "location_type_business": "Residential"},
        {"id": 129, "name": "Purasawalkam",      "city_id": 6, "city_division_name": "Central Chennai", "location_type_business": "Commercial"},
        {"id": 130, "name": "Tambaram",          "city_id": 6, "city_division_name": "South Chennai",   "location_type_business": "Peripheral"},
        {"id": 131, "name": "T Nagar",           "city_id": 6, "city_division_name": "Central Chennai", "location_type_business": "Commercial"},
        {"id": 132, "name": "Velachery",         "city_id": 6, "city_division_name": "South Chennai",   "location_type_business": "Commercial"},
        {"id": 133, "name": "Villivakkam",       "city_id": 6, "city_division_name": "West Chennai",    "location_type_business": "Residential"},
    ]
    existing_ids = {row.id for row in db.query(Location.id).all()}
    for loc in locations:
        if loc["id"] not in existing_ids:
            db.add(Location(**loc))
    db.commit()
    print(f"  Locations seeded.")
